"""
Django settings for jarvisWuodPWebsite project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

import environ
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'meta',

    'portfolio.apps.PortfolioConfig',
]

# SEO STAFF BOOSTER
META_SITE_PROTOCOL = 'https'
META_SITE_DOMAIN = 'jarviswuod.com'
META_DEFAULT_KEYWORDS = ['jarvis wuod', 'mentorship africa', 'free mentorship program', 'software programming,' 'resume review', 'linkedin revamp', 'world best tech mentor', 'why you need a mentor in tech', 'tech mentorship', 'developer mentorship', 'software developer mentor', 'coding help', 'hire a developer', 'coding mentor', 'tech mentor africa', 'web development mentorship', 'full-stack development', 'full-stack  mentor', 'resume optimization', 'career guidance', 'frontend mentor', 'freelance developer', 'software developer for hire',
                         'best software developer', 'developer from africa', 'coding bootcamp alternative', 'personalized tech mentorship', 'tech career coaching', 'web developer portfolio', 'tech job application help', 'android app development mentor',  'software engineering mentorship', 'coding interview preparation', 'tech industry insights', 'software project guidance', 'programming language mentorship', 'tech career advancement', 'software development best practices', 'coding skills improvement', 'tech networking opportunities', 'software development resources']

META_DEFAULT_TITLE = 'Jarvis Wuod | Ultimate guide to learning web development, land your first job and get to convert your ideas into website you will fall in love with'
META_DEFAULT_IMAGE = 'https://jarviswuod.com/static/logo_.png'
META_DEFAULT_URL = 'https://jarviswuod.com'
META_DEFAULT_AUTHOR = 'Jarvis Wuod'
META_DEFAULT_DESCRIPTION = 'Your site default description'
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jarvisWuodPWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR, 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jarvisWuodPWebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'
MEDIA_URL = 'images/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
